# ~/.config/hypr/hyprsunset.conf

# Night profile: Triggers at 9:00 PM
profile {
    time = 21:00
    temperature = 4000     # Adjust Kelvin here (lower is warmer/more orange)
}

# Day profile: Triggers at 6:00 AM
profile {
    time = 6:00
    identity = true        # Bypasses the filter back to stock monitor colors
}
